### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery     at bootstrap.min.js:6:37?

### ISSUE THREAD

**Issue by YANGJINJUE** [jstack-review/jstack-review#16]
https://jstack.review/  <img width="530" alt="image" src="https://user-images.githubusercontent.com/32013488/222312191-0cc7bd2e-fa0b-4309-bc6d-a620ee8f825e.png">

**Comment by elmuerte** [comment]
Cannot reproduce, and seeing the error above it about a connection reset, that is probably the cause.
