### ISSUE TITLE
JavaScript Error when clicking 'Analyze' Button

### ISSUE THREAD

**Issue by aaronols** [jstack-review/jstack-review#7]
When clicking the 'Analyze' Button, nothing happens.
The following error is printed to the JavaScript Console:
```
Uncaught TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (mustache.min.js:1)
    at executeAnalysis (frontend.js:140)
    at HTMLButtonElement.<anonymous> (frontend.js:50)
    at HTMLButtonElement.dispatch (jquery-1.12.4.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.12.4.min.js:3)
```

This happens with Chrome 77 and Firefox 69.

**Comment by elmuerte** [comment]
Missing closing script tag hid the error template which was used.
The posted analysis apparently did not contain and threads.
The above error has been fixed.

**Comment by aaronols** [comment]
Thanks, can confirm that an error message is now displayed. 👍
